In [1]:
import pickle

In [2]:
with open('./no_data_orchestra.pickle', 'rb') as handle:
    orchestra = pickle.load(handle)

In [7]:
from dtw import dtw

In [14]:
import numpy as np

In [74]:
fl = orchestra['flute']['normal']['mf'][78]['peaks']

In [75]:
fl2 = orchestra['cymbal']['normal']['mf'][60]['peaks']

In [71]:
idxes = np.linspace(1,12, 12)

In [76]:
dist = dtw(fl, fl2, dist=lambda x, y: np.linalg.norm(x - y, ord=1))

ValueError: operands could not be broadcast together with shapes (18,) (17,) 

In [73]:
dist

(14096.6504942006,
 array([[    0.        ,  3800.36714615],
        [12533.94740917, 14096.6504942 ]]),
 array([[    0.        ,  3800.36714615],
        [12533.94740917, 14096.6504942 ]]),
 (array([0, 1]), array([0, 1])))